## LinearRegression(),SVM(),RandomForestClassifier()

In [113]:
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_digits
digits=load_digits()

In [115]:
from sklearn.model_selection import train_test_split

In [117]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.33, random_state=42)

In [151]:
# Faced an error for limited iterations so had to use this
lr=LogisticRegression(max_iter=1000) 
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9148580968280468

In [153]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9549248747913188

In [155]:
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9315525876460768

In [157]:
from sklearn.model_selection import KFold

In [159]:
kf=KFold(n_splits=3, random_state=None, shuffle=False)

In [161]:
>>> for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
...  
...     print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [163]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [165]:
get_score(lr,X_train,X_test,y_train,y_test)

0.9148580968280468

In [167]:
get_score(svm,X_train,X_test,y_train,y_test)

0.9549248747913188

In [169]:
get_score(rfc,X_train,X_test,y_train,y_test)

0.9298831385642737

In [171]:
from sklearn.model_selection import StratifiedKFold

In [173]:
stf=StratifiedKFold(n_splits=3)

In [175]:
scores_lr=[]
scores_svm=[]
scores_rfc=[]
for train_index, test_index in kf.split(digits.data) :
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(lr,X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(svm,X_train,X_test,y_train,y_test))
    scores_rfc.append(get_score(rfc,X_train,X_test,y_train,y_test))
# The use of max_iter=1000 parameter in LogisticRegression() helped solve the issue for limited iterations. Chnage/Remove the iterations to understand the error

In [178]:
scores_lr,scores_svm,scores_rfc

([0.9248747913188647, 0.9432387312186978, 0.9148580968280468],
 [0.9666110183639399, 0.9816360601001669, 0.9549248747913188],
 [0.9415692821368948, 0.9565943238731218, 0.9232053422370617])

## CrossValScore

In [185]:
# Instead calculating all like in above using a crossvalscore to compare is a built in package

In [187]:
from sklearn.model_selection import cross_val_score

In [193]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [195]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [203]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target).round(3)

array([0.922, 0.911, 0.958, 0.967, 0.914])