In [4]:
import pandas as pd
import numpy as np

In [19]:
miles=pd.DataFrame({"farthest_run_mile":[50,62,np.nan,30,56,87,103,50]})

In [21]:
from sklearn.impute import SimpleImputer

In [23]:
imp_mean=SimpleImputer(strategy='mean')

In [25]:
miles

farthest_run_mile
0               50.0
1               62.0
2                NaN
3               30.0
4               56.0
5               87.0
6              103.0
7               50.0

In [27]:
miles.isna().sum()

farthest_run_mile    1
dtype: int64

In [29]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 62.57142857],
       [ 30.        ],
       [ 56.        ],
       [ 87.        ],
       [103.        ],
       [ 50.        ]])

In [32]:
imp_median=SimpleImputer(strategy='median')

In [34]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 56.],
       [ 30.],
       [ 56.],
       [ 87.],
       [103.],
       [ 50.]])

In [52]:
imp_mode=SimpleImputer(strategy='most_frequent')

In [54]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [ 30.],
       [ 56.],
       [ 87.],
       [103.],
       [ 50.]])

In [58]:
imp_conste=SimpleImputer(strategy='constant',fill_value=13)

In [60]:
imp_conste.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [ 30.],
       [ 56.],
       [ 87.],
       [103.],
       [ 50.]])

In [64]:
#Now for strings
names=pd.DataFrame({'names':['Alan','Walker','Milo',np.nan,'Suraj','Jaya']})

In [66]:
names

names
0    Alan
1  Walker
2    Milo
3     NaN
4   Suraj
5    Jaya

In [76]:
imp_const_cat=SimpleImputer(strategy='constant',fill_value='cat')

In [78]:
imp_const_cat.fit_transform(names)

array([['Alan'],
       ['Walker'],
       ['Milo'],
       ['cat'],
       ['Suraj'],
       ['Jaya']], dtype=object)

In [80]:
imp_mean_add=SimpleImputer(strategy='mean',add_indicator=True)

In [82]:
imp_mean_add.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 62.57142857,   1.        ],
       [ 30.        ,   0.        ],
       [ 56.        ,   0.        ],
       [ 87.        ,   0.        ],
       [103.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [10]:
# We do not have the dataset but this is how we can use the column_transformer and the video reference is https://youtu.be/0Hsj0h-tXAY?si=Wj2Kto3bbCngIUo5&t=585

In [6]:
df = pd.read_csv('simple_imputer_csv.csv')

In [ ]:
from sklearn.compose import make_column_transformer

In [ ]:
ct = make_column_transformer( (imp_constant_cat, ['Name']), (imp_mean, ['farthest_run_mi']), remainder='drop')

In [ ]:
ct.set_output(transform="pandas")

In [ ]:
df_pandas = ct.fit_transform(df)

In [ ]:
df_pandas